#define CX 72
#define CY 84
#define W 144
#define H 168
#define RAD 72

//#define INF int32_t 2972590818  //148204965966  // a long time from now.

const GPathInfo FULL_DAY_PATH_INFO = {
  .num_points = 4,
  .points = (GPoint []) { {0, 0}, {W, 0}, {W, H}, {0, H} }
};

//const GPathInfo FULL_NIGHT_PATH_INFO = {
//  .num_points = 3,
//  .points = (GPoint []) { {-1, -1}, {-4, -1}, {-4, -5} }
//};

/*
image_types:
  0 new
  1 waxing crescent
  2 first quarter
  3 waxing gibbous
  4 full
  5 waning gibbous
  6 third quarter
  7 waning crescent

image_rotations:
  0 sun at 00
  1 sun at 03
  2 sun at 06
  3 sun at 09
  4 sun at 12
  5 sun at 15
  6 sun at 18
  7 sun at 21
*/

const uint32_t MOON_IDS[8][8][2] = {          // [phase][rotation][color]
  {
    {RESOURCE_ID_NEW_B, RESOURCE_ID_NEW_W},
    {RESOURCE_ID_NEW_B, RESOURCE_ID_NEW_W},
    {RESOURCE_ID_NEW_B, RESOURCE_ID_NEW_W},
    {RESOURCE_ID_NEW_B, RESOURCE_ID_NEW_W},
    {RESOURCE_ID_NEW_B, RESOURCE_ID_NEW_W},
    {RESOURCE_ID_NEW_B, RESOURCE_ID_NEW_W},
    {RESOURCE_ID_NEW_B, RESOURCE_ID_NEW_W},
    {RESOURCE_ID_NEW_B, RESOURCE_ID_NEW_W}
  },
  {
    {RESOURCE_ID_CRESCENT_0_B, RESOURCE_ID_CRESCENT_0_W},
    {RESOURCE_ID_CRESCENT_1_B, RESOURCE_ID_CRESCENT_1_W},
    {RESOURCE_ID_CRESCENT_2_B, RESOURCE_ID_CRESCENT_2_W},
    {RESOURCE_ID_CRESCENT_3_B, RESOURCE_ID_CRESCENT_3_W},
    {RESOURCE_ID_CRESCENT_4_B, RESOURCE_ID_CRESCENT_4_W},
    {RESOURCE_ID_CRESCENT_5_B, RESOURCE_ID_CRESCENT_5_W},
    {RESOURCE_ID_CRESCENT_6_B, RESOURCE_ID_CRESCENT_6_W},
    {RESOURCE_ID_CRESCENT_7_B, RESOURCE_ID_CRESCENT_7_W}
  },
  {
    {RESOURCE_ID_QUARTER_0_B, RESOURCE_ID_QUARTER_0_W},
    {RESOURCE_ID_QUARTER_1_B, RESOURCE_ID_QUARTER_1_W},
    {RESOURCE_ID_QUARTER_2_B, RESOURCE_ID_QUARTER_2_W},
    {RESOURCE_ID_QUARTER_3_B, RESOURCE_ID_QUARTER_3_W},
    {RESOURCE_ID_QUARTER_4_B, RESOURCE_ID_QUARTER_4_W},
    {RESOURCE_ID_QUARTER_5_B, RESOURCE_ID_QUARTER_5_W},
    {RESOURCE_ID_QUARTER_6_B, RESOURCE_ID_QUARTER_6_W},
    {RESOURCE_ID_QUARTER_7_B, RESOURCE_ID_QUARTER_7_W}
  },
  {
    {RESOURCE_ID_GIBBOUS_0_B, RESOURCE_ID_GIBBOUS_0_W},
    {RESOURCE_ID_GIBBOUS_1_B, RESOURCE_ID_GIBBOUS_1_W},
    {RESOURCE_ID_GIBBOUS_2_B, RESOURCE_ID_GIBBOUS_2_W},
    {RESOURCE_ID_GIBBOUS_3_B, RESOURCE_ID_GIBBOUS_3_W},
    {RESOURCE_ID_GIBBOUS_4_B, RESOURCE_ID_GIBBOUS_4_W},
    {RESOURCE_ID_GIBBOUS_5_B, RESOURCE_ID_GIBBOUS_5_W},
    {RESOURCE_ID_GIBBOUS_6_B, RESOURCE_ID_GIBBOUS_6_W},
    {RESOURCE_ID_GIBBOUS_7_B, RESOURCE_ID_GIBBOUS_7_W}
  },
  {
    {RESOURCE_ID_FULL_B, RESOURCE_ID_FULL_W},
    {RESOURCE_ID_FULL_B, RESOURCE_ID_FULL_W},
    {RESOURCE_ID_FULL_B, RESOURCE_ID_FULL_W},
    {RESOURCE_ID_FULL_B, RESOURCE_ID_FULL_W},
    {RESOURCE_ID_FULL_B, RESOURCE_ID_FULL_W},
    {RESOURCE_ID_FULL_B, RESOURCE_ID_FULL_W},
    {RESOURCE_ID_FULL_B, RESOURCE_ID_FULL_W},
    {RESOURCE_ID_FULL_B, RESOURCE_ID_FULL_W}
  },
  {
    {RESOURCE_ID_GIBBOUS_6_B, RESOURCE_ID_GIBBOUS_6_W},
    {RESOURCE_ID_GIBBOUS_7_B, RESOURCE_ID_GIBBOUS_7_W},
    {RESOURCE_ID_GIBBOUS_0_B, RESOURCE_ID_GIBBOUS_0_W},
    {RESOURCE_ID_GIBBOUS_1_B, RESOURCE_ID_GIBBOUS_1_W},
    {RESOURCE_ID_GIBBOUS_2_B, RESOURCE_ID_GIBBOUS_2_W},
    {RESOURCE_ID_GIBBOUS_3_B, RESOURCE_ID_GIBBOUS_3_W},
    {RESOURCE_ID_GIBBOUS_4_B, RESOURCE_ID_GIBBOUS_4_W},
    {RESOURCE_ID_GIBBOUS_5_B, RESOURCE_ID_GIBBOUS_5_W}
  },
  {
    {RESOURCE_ID_QUARTER_4_B, RESOURCE_ID_QUARTER_4_W},
    {RESOURCE_ID_QUARTER_5_B, RESOURCE_ID_QUARTER_5_W},
    {RESOURCE_ID_QUARTER_6_B, RESOURCE_ID_QUARTER_6_W},
    {RESOURCE_ID_QUARTER_7_B, RESOURCE_ID_QUARTER_7_W},
    {RESOURCE_ID_QUARTER_0_B, RESOURCE_ID_QUARTER_0_W},
    {RESOURCE_ID_QUARTER_1_B, RESOURCE_ID_QUARTER_1_W},
    {RESOURCE_ID_QUARTER_2_B, RESOURCE_ID_QUARTER_2_W},
    {RESOURCE_ID_QUARTER_3_B, RESOURCE_ID_QUARTER_3_W}
  },
  {
    {RESOURCE_ID_CRESCENT_2_B, RESOURCE_ID_CRESCENT_2_W},
    {RESOURCE_ID_CRESCENT_3_B, RESOURCE_ID_CRESCENT_3_W},
    {RESOURCE_ID_CRESCENT_4_B, RESOURCE_ID_CRESCENT_4_W},
    {RESOURCE_ID_CRESCENT_5_B, RESOURCE_ID_CRESCENT_5_W},
    {RESOURCE_ID_CRESCENT_6_B, RESOURCE_ID_CRESCENT_6_W},
    {RESOURCE_ID_CRESCENT_7_B, RESOURCE_ID_CRESCENT_7_W},
    {RESOURCE_ID_CRESCENT_0_B, RESOURCE_ID_CRESCENT_0_W},
    {RESOURCE_ID_CRESCENT_1_B, RESOURCE_ID_CRESCENT_1_W}
  }
};